<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CareerTableSeeder extends Seeder {

	public function run()
	{
		DB::table('career')->truncate();

		$career = [
		[
		'title'          => 'This is the anoucement from the Server',
		'banner'         => '',
		'attribute'      => 'Lorem ipsum dolor sit amet, consectetur adipisicing',
		'author'         => 'Sarawut Popadcha',
		'gender'		 => 'Male',
		'age'			 => 'Age',
		'qualifications' => 'Degree',
		'wage_1'		 => 'wage_1',
		'wage_2'		 => 'wage_2',
		'wage_3'		 => 'wage_3',
		'wage_4'		 => 'wage_4',
		'wage_5'		 => 'wage_5',
		'wage_6'		 => 'wage_6',
		'wage_7'		 => 'wage_7',
		'wage_8'		 => 'wage_8',
		'wage_9'		 => 'wage_9',
		'wage_10'		 => 'wage_10',
		'wage_11'		 => 'wage_11',
		'wage_12'		 => 'wage_12',
		'wage_13'		 => 'wage_13',
		'wage_14'		 => 'wage_14',
		'wage_15'		 => 'wage_15',
		'wage_16'		 => 'wage_16',
		'person_id'		 => 'Person',
		'published_date' => Carbon\Carbon::now(),
		'created_at'     => Carbon\Carbon::now()->subWeek(),
		'updated_at'     => Carbon\Carbon::now()->subWeek(),
		],
		[
		'title'          => 'This is the anoucement from the Server',
		'banner'         => '',
		'attribute'      => 'Lorem ipsum dolor sit amet, consectetur adipisicing',
		'author'         => 'Sarawut Popadcha',
		'gender'		 => 'Male',
		'age'			 => 'Age',
		'qualifications' => 'Degree',
		'wage_1'		 => 'wage_1',
		'wage_2'		 => 'wage_2',
		'wage_3'		 => 'wage_3',
		'wage_4'		 => 'wage_4',
		'wage_5'		 => 'wage_5',
		'wage_6'		 => 'wage_6',
		'wage_7'		 => 'wage_7',
		'wage_8'		 => 'wage_8',
		'wage_9'		 => 'wage_9',
		'wage_10'		 => 'wage_10',
		'wage_11'		 => 'wage_11',
		'wage_12'		 => 'wage_12',
		'wage_13'		 => 'wage_13',
		'wage_14'		 => 'wage_14',
		'wage_15'		 => 'wage_15',
		'wage_16'		 => 'wage_16',
		'person_id'		 => 'Person',
		'published_date' => Carbon\Carbon::now(),
		'created_at'     => Carbon\Carbon::now()->subWeek(),
		'updated_at'     => Carbon\Carbon::now()->subWeek(),
		],
		[
		'title'          => 'This is the anoucement from the Server',
		'banner'         => '',
		'attribute'      => 'Lorem ipsum dolor sit amet, consectetur adipisicing',
		'author'         => 'Sarawut Popadcha',
		'gender'		 => 'Male',
		'age'			 => 'Age',
		'qualifications' => 'Degree',
		'wage_1'		 => 'wage_1',
		'wage_2'		 => 'wage_2',
		'wage_3'		 => 'wage_3',
		'wage_4'		 => 'wage_4',
		'wage_5'		 => 'wage_5',
		'wage_6'		 => 'wage_6',
		'wage_7'		 => 'wage_7',
		'wage_8'		 => 'wage_8',
		'wage_9'		 => 'wage_9',
		'wage_10'		 => 'wage_10',
		'wage_11'		 => 'wage_11',
		'wage_12'		 => 'wage_12',
		'wage_13'		 => 'wage_13',
		'wage_14'		 => 'wage_14',
		'wage_15'		 => 'wage_15',
		'wage_16'		 => 'wage_16',
		'person_id'		 => 'Person',
		'published_date' => Carbon\Carbon::now(),
		'created_at'     => Carbon\Carbon::now()->subWeek(),
		'updated_at'     => Carbon\Carbon::now()->subWeek(),
		],
		[
		'title'          => 'This is the anoucement from the Server',
		'banner'         => '',
		'attribute'      => 'Lorem ipsum dolor sit amet, consectetur adipisicing',
		'author'         => 'Sarawut Popadcha',
		'gender'		 => 'Male',
		'age'			 => 'Age',
		'qualifications' => 'Degree',
		'wage_1'		 => 'wage_1',
		'wage_2'		 => 'wage_2',
		'wage_3'		 => 'wage_3',
		'wage_4'		 => 'wage_4',
		'wage_5'		 => 'wage_5',
		'wage_6'		 => 'wage_6',
		'wage_7'		 => 'wage_7',
		'wage_8'		 => 'wage_8',
		'wage_9'		 => 'wage_9',
		'wage_10'		 => 'wage_10',
		'wage_11'		 => 'wage_11',
		'wage_12'		 => 'wage_12',
		'wage_13'		 => 'wage_13',
		'wage_14'		 => 'wage_14',
		'wage_15'		 => 'wage_15',
		'wage_16'		 => 'wage_16',
		'person_id'		 => 'Person',
		'published_date' => Carbon\Carbon::now(),
		'created_at'     => Carbon\Carbon::now()->subWeek(),
		'updated_at'     => Carbon\Carbon::now()->subWeek(),
		],
		[
		'title'          => 'This is the anoucement from the Server',
		'banner'         => '',
		'attribute'      => 'Lorem ipsum dolor sit amet, consectetur adipisicing',
		'author'         => 'Sarawut Popadcha',
		'gender'		 => 'Male',
		'age'			 => 'Age',
		'qualifications' => 'Degree',
		'wage_1'		 => 'wage_1',
		'wage_2'		 => 'wage_2',
		'wage_3'		 => 'wage_3',
		'wage_4'		 => 'wage_4',
		'wage_5'		 => 'wage_5',
		'wage_6'		 => 'wage_6',
		'wage_7'		 => 'wage_7',
		'wage_8'		 => 'wage_8',
		'wage_9'		 => 'wage_9',
		'wage_10'		 => 'wage_10',
		'wage_11'		 => 'wage_11',
		'wage_12'		 => 'wage_12',
		'wage_13'		 => 'wage_13',
		'wage_14'		 => 'wage_14',
		'wage_15'		 => 'wage_15',
		'wage_16'		 => 'wage_16',
		'person_id'		 => 'Person',
		'published_date' => Carbon\Carbon::now(),
		'created_at'     => Carbon\Carbon::now()->subWeek(),
		'updated_at'     => Carbon\Carbon::now()->subWeek(),
		],
		[
		'title'          => 'This is the anoucement from the Server',
		'banner'         => '',
		'attribute'      => 'Lorem ipsum dolor sit amet, consectetur adipisicing',
		'author'         => 'Sarawut Popadcha',
		'gender'		 => 'Male',
		'age'			 => 'Age',
		'qualifications' => 'Degree',
		'wage_1'		 => 'wage_1',
		'wage_2'		 => 'wage_2',
		'wage_3'		 => 'wage_3',
		'wage_4'		 => 'wage_4',
		'wage_5'		 => 'wage_5',
		'wage_6'		 => 'wage_6',
		'wage_7'		 => 'wage_7',
		'wage_8'		 => 'wage_8',
		'wage_9'		 => 'wage_9',
		'wage_10'		 => 'wage_10',
		'wage_11'		 => 'wage_11',
		'wage_12'		 => 'wage_12',
		'wage_13'		 => 'wage_13',
		'wage_14'		 => 'wage_14',
		'wage_15'		 => 'wage_15',
		'wage_16'		 => 'wage_16',
		'person_id'		 => 'Person',
		'published_date' => Carbon\Carbon::now(),
		'created_at'     => Carbon\Carbon::now()->subWeek(),
		'updated_at'     => Carbon\Carbon::now()->subWeek(),
		],
		[
		'title'          => 'This is the anoucement from the Server',
		'banner'         => '',
		'attribute'      => 'Lorem ipsum dolor sit amet, consectetur adipisicing',
		'author'         => 'Sarawut Popadcha',
		'gender'		 => 'Male',
		'age'			 => 'Age',
		'qualifications' => 'Degree',
		'wage_1'		 => 'wage_1',
		'wage_2'		 => 'wage_2',
		'wage_3'		 => 'wage_3',
		'wage_4'		 => 'wage_4',
		'wage_5'		 => 'wage_5',
		'wage_6'		 => 'wage_6',
		'wage_7'		 => 'wage_7',
		'wage_8'		 => 'wage_8',
		'wage_9'		 => 'wage_9',
		'wage_10'		 => 'wage_10',
		'wage_11'		 => 'wage_11',
		'wage_12'		 => 'wage_12',
		'wage_13'		 => 'wage_13',
		'wage_14'		 => 'wage_14',
		'wage_15'		 => 'wage_15',
		'wage_16'		 => 'wage_16',
		'person_id'		 => 'Person',
		'published_date' => Carbon\Carbon::now(),
		'created_at'     => Carbon\Carbon::now()->subWeek(),
		'updated_at'     => Carbon\Carbon::now()->subWeek(),
		]
		];

		DB::table('career')->insert($career);
	}
}